export enum Fields {
  SCIENCE = 'SCIENCE',
  MIND = 'PHILOSOPHY',
  SPIRITUALITY = 'SPIRITUALITY',
  THEOLOGY = 'THEOLOGY',
  HISTORY = 'HISTORY',
  METAPHYSICS = 'METAPHYSICS',
  MUSIC = 'MUSIC',
  POLITICS = 'POLITICS',
}

export enum Region {
  EUROPE = 'EUROPE',
  MIDDLE_EAST = 'MIDDLE_EAST',
  AFRICA = 'AFRICA',
  NORTH_AMERICA = 'NORTH_AMERICA',
}
export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum EventId {
  // span events
  CHRISTIAN_DOMINATION_INSTITUTIONS = 'CHRISTIAN_DOMINATION_INSTITUTIONS',
  ISLAMIC_GOLDEN_AGE = 'ISLAMIC_GOLDEN_AGE',
  ROMAN_REPUBLIC = 'ROMAN_REPUBLIC',
  ROMAN_EMPIRE = 'ROMAN_EMPIRE',
  CAROLOGIAN_RENAISSANCE = 'CAROLOGIAN_RENAISSANCE',
  TWELVE_CENTURY_RENAISSANCE = 'TWELVE_CENTURY_RENAISSANCE',
  ITALIAN_RENAISSANCE = 'ITALIAN_RENAISSANCE',
  DARK_AGES = 'DARK_AGES',
  CHRISTIAN_INQUISITION = 'CHRISTIAN_INQUISITION',
  // year events
  CHRISTIANITY_APPEARS = 'CHRISTIANITY_APPEARS',
  CHRISTIANITY_MADE_OFFICAL_STATE_RELIGION = 'CHRISTIANITY_MADE_OFFICAL_STATE_RELIGION',
  CHRISTIANITY_BANS_OLYMPIC_GAMES = 'CHRISTIANITY_BANS_OLYMPIC_GAMES',
  ROMAN_EMPIRE_ADOPTS_CHRISTIANITY = 'ROMAN_EMPIRE_ADOPTS_CHRISTIANITY',
  FALL_OF_CONSTANTINOPLE = 'FALL_OF_CONSTANTINOPLE',
  PROTESTANT_REFORMATION = 'PROTESTANT_REFORMATION',
  JUSTINIAN_CLOSES_ACADEMY_OF_ATHENS = 'JUSTINIAN_CLOSES_ACADEMY_OF_ATHENS',
  PAGANISM_BANNED = 'PAGANISM_BANNED',
  ALTAR_OF_VICTORY_REMOVED = 'ALTAR_OF_VICTORY_REMOVED',
  CALIPH_AL_MUTAWAKKIL_DENOUNCES_RATIONALISM = 'CALIPH_AL_MUTAWAKKIL_DENOUNCES_RATIONALISM',
  CALIPH_AL_QADIR_REJECTS_RATIONALISM = 'CALIPH_AL_QADIR_REJECTS_RATIONALISM',
}
