export enum Fields {
  SCIENCE = 'Science',
  MIND = 'Philosophy',
  SPIRITUALITY = 'Spirituality',
  THEOLOGY = 'Theology',
  HISTORY = 'History',
  METAPHYSICS = 'Metaphysics',
  MUSIC = 'Music',
  POLITICS = 'Politics',
}

export enum Region {
  EUROPE = 'Europe',
  MIDDLE_EAST = 'Middle East',
}

export enum Religion {
  POLYTHEIST = 'Polytheist',
  CHRISTIAN = 'Christian',
  MUSLIM = 'Muslim',
  JEWISH = 'Jewish',
  ATHEIST = 'Atheist',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum EventType {
  EVENT_SPAN = 'EVENT_SPAN',
  EVENT_YEAR = 'EVENT_YEAR',
  PEOPLE_LIST = 'PEOPLE_LIST',
}

export enum EventId {
  // span events
  CHRISTIAN_DOMINATION_INSTITUTIONS = 'CHRISTIAN_DOMINATION_INSTITUTIONS',
  ISLAMIC_GOLDEN_AGE = 'ISLAMIC_GOLDEN_AGE',
  ROMAN_REPUBLIC = 'ROMAN_REPUBLIC',
  ROMAN_EMPIRE = 'ROMAN_EMPIRE',
  CAROLOGIAN_RENAISSANCE = 'CAROLOGIAN_RENAISSANCE',
  NORTHERN_CRUSADES = 'NORTHERN_CRUSADES',
  PERSECUTION_OF_POLYTHEISTS = 'PERSECUTION_OF_POLYTHEISTS',
  TWELVE_CENTURY_RENAISSANCE = 'TWELVE_CENTURY_RENAISSANCE',
  ITALIAN_RENAISSANCE = 'ITALIAN_RENAISSANCE',
  DARK_AGES = 'DARK_AGES',
  CHRISTIAN_INQUISITION = 'CHRISTIAN_INQUISITION',
  PAX_ROMANA = 'PAX_ROMANA',
  AMBROSE_OF_MILAN = 'AMBROSE_OF_MILAN',
  WITCH_HUNTS = 'WITCH_HUNTS',
  SCIENTIFIC_REVOLUTION = 'SCIENTIFIC_REVOLUTION',
  INDUSTRIAL_REVOLUTION = 'INDUSTRIAL_REVOLUTION',
  // year events
  CHRISTIANITY_APPEARS = 'CHRISTIANITY_APPEARS',
  SECOND_TEMPLE_DESTROYED = 'SECOND_TEMPLE_DESTROYED',
  ROME_CONQUERS_JUDEA = 'ROME_CONQUERS_JUDEA',
  CHRISTIANITY_MADE_OFFICAL_STATE_RELIGION = 'CHRISTIANITY_MADE_OFFICAL_STATE_RELIGION',
  PENALTY_OF_DEATH_FOR_PAGANS_ENACTED = 'PENALTY_OF_DEATH_FOR_PAGANS_ENACTED',
  LIBRARY_OF_ANTIOCH_DESTROYED = 'LIBRARY_OF_ANTIOCH_DESTROYED',
  THE_TERM_PAGAN_IS_INTRODUCED = 'THE_TERM_PAGAN_IS_INTRODUCED',
  CHRISTIANITY_BANS_OLYMPIC_GAMES = 'CHRISTIANITY_BANS_OLYMPIC_GAMES',
  CONSTANTINE_ADOPTS_CHRISTIANITY = 'CONSTANTINE_ADOPTS_CHRISTIANITY',
  CHRISTIANITY_BECOMES_MANDATORY = 'CHRISTIANITY_BECOMES_MANDATORY',
  SERAPEUM_DESTROYED = 'SERAPEUM_DESTROYED',
  BOOK_BURNINGS = 'BOOK_BURNINGS',
  FALL_OF_CONSTANTINOPLE = 'FALL_OF_CONSTANTINOPLE',
  PROTESTANT_REFORMATION = 'PROTESTANT_REFORMATION',
  JUSTINIAN_CLOSES_ACADEMY_OF_ATHENS = 'JUSTINIAN_CLOSES_ACADEMY_OF_ATHENS',
  MEDICI_REOPENS_PLATONIC_ACADEMY = 'MEDICI_REOPENS_PLATONIC_ACADEMY',
  PAGANISM_BANNED = 'PAGANISM_BANNED',
  ALTAR_OF_VICTORY_REMOVED = 'ALTAR_OF_VICTORY_REMOVED',
  CALIPH_AL_MUTAWAKKIL_REJECTS_RATIONALISM = 'CALIPH_AL_MUTAWAKKIL_REJECTS_RATIONALISM',
  CALIPH_AL_QADIR_REJECTS_RATIONALISM = 'CALIPH_AL_QADIR_REJECTS_RATIONALISM',
  PLETHON_VISITS_FLORENCE = 'PLETHON_VISITS_FLORENCE',
}
